export const HomeActions = {
  SET_INTRO_STATUS: "SET_INTRO_STATUS",
  GET_CONFIG: "GET_CONFIG",
  SEARCH_AGENTS: "SEARCH_AGENTS",
  GET_AGENTS_LIST: "GET_AGENTS_LIST",
  OPEN_MAP: "OPEN_MAP",
  FORCE_CLOSE_LOADING: "FORCE_CLOSE_LOADING",
  SET_SELECTED_COORDINATE: "SET_SELECTED_COORDINATE",
  CLEAR_SEARCH_DATA: "CLEAR_SEARCH_DATA",
  GET_APPOINTMENT: "GET_APPOINTMENT",
  GET_APPOINTMENT_DETAIl: "GET_APPOINTMENT_DETAIl",
  SELECT_PAYMENT_ID: "SELECT_PAYMENT_ID",
  SET_CURRENT_LOCATION: "SET_CURRENT_LOCATION",
  GET_TOTAL_SERVICES: "GET_TOTAL_SERVICES",
  SET_SEARCH_SERVICE: "SET_SEARCH_SERVICE",
  RESET_SEARCH_SERVICE: "RESET_SEARCH_SERVICE"
};